#!/bin/bash
# Keel Setup Wizard - Test Version with Automated Inputs
# Demonstrates the complete setup flow

set -e

# Test directory
TEST_DIR="/tmp/keel-setup-test"
mkdir -p "$TEST_DIR"
cd "$TEST_DIR"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       Keel AI-SDLC Framework - Setup Wizard TEST                ║"
echo "║                                                                ║"
echo "║  Running with automated inputs to demonstrate workflow         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

success() {
  echo -e "${GREEN}✅ $1${NC}"
}

warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

error() {
  echo -e "${RED}❌ $1${NC}"
}

section_header() {
  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
}

# ==============================================================================
# AUTOMATED TEST INPUTS
# ==============================================================================
section_header "STEP 1: Choose Installation Method"

echo "Simulating user selection: Option 1 (Claude Code Skill)"
echo ""
INSTALL_TYPE="claude-code-skill"
success "Selected: Claude Code Skill"
echo ""

# ==============================================================================
# STEP 2: Verify Prerequisites
# ==============================================================================
section_header "STEP 2: Verify Prerequisites"

echo "Checking requirements..."
echo ""

if command -v git &> /dev/null; then
  success "Git $(git --version | awk '{print $3}')"
else
  warning "Git not available in test environment"
fi

if command -v node &> /dev/null; then
  success "Node.js $(node --version)"
else
  warning "Node.js not available in test environment"
fi

echo ""
success "Prerequisites verified"
echo ""

# ==============================================================================
# STEP 3: Configure Project
# ==============================================================================
section_header "STEP 3: Configure Your Project"

echo "Simulating user inputs:"
echo ""

PROJECT_NAME="my-keel-project"
STACK="cakephp"

success "Project name: $PROJECT_NAME"
success "Stack: $STACK (CakePHP 4.4 + PHP 8.1)"
echo ""

# ==============================================================================
# STEP 4: Configure Integrations
# ==============================================================================
section_header "STEP 4: Configure Optional Integrations"

echo "Setting up integrations..."
echo ""

# Jira
JIRA_CONFIG="true"
JIRA_URL="https://company.atlassian.net"
JIRA_EMAIL="user@company.com"
success "Jira configured"
echo "  URL: $JIRA_URL"
echo "  Email: $JIRA_EMAIL"
echo "  Token: (stored securely)"
echo ""

# Playwright
PLAYWRIGHT_CONFIG="true"
PW_CHROMIUM="true"
PW_FIREFOX="false"
PW_WEBKIT="false"
PW_HEADLESS="true"
success "Playwright configured"
echo "  Headless: Yes"
echo "  Browsers: Chromium ✓, Firefox ✗, WebKit ✗"
echo ""

# GitHub
GITHUB_CONFIG="true"
GITHUB_REPO="mycompany/my-project"
success "GitHub configured"
echo "  Repository: $GITHUB_REPO"
echo "  Token: (stored securely)"
echo ""

# Slack
SLACK_CONFIG="false"
warning "Slack integration skipped"
echo ""

# ==============================================================================
# STEP 5: Install Keel
# ==============================================================================
section_header "STEP 5: Install Keel Framework"

echo "Simulating installation..."
echo ""
success "Keel installation completed"
echo "  Type: Claude Code Skill"
echo "  Location: ~/.claude/skills/keel-framework"
echo ""

# ==============================================================================
# STEP 6: Create Configuration Files
# ==============================================================================
section_header "STEP 6: Create Configuration Files"

echo "Generating configuration files..."
echo ""

# Create .keel directory
KEEL_CONFIG_DIR=".keel"
mkdir -p "$KEEL_CONFIG_DIR/config"
mkdir -p "$KEEL_CONFIG_DIR/secrets"

# Main config file
cat > "$KEEL_CONFIG_DIR/keel.config.yml" << 'EOF'
# Keel AI-SDLC Framework Configuration
# Generated by setup wizard - 2026-07-07

project:
  name: "my-keel-project"
  stack: "cakephp"
  created_at: "2026-07-07"

integrations:
  jira:
    enabled: true
    url: "https://company.atlassian.net"
    email: "user@company.com"
    # API token stored in: ~/.keel/secrets/jira.token

  playwright:
    enabled: true
    headless: true
    browsers:
      chromium: true
      firefox: false
      webkit: false

  github:
    enabled: true
    repository: "mycompany/my-project"
    # Token stored in: ~/.keel/secrets/github.token

  slack:
    enabled: false
EOF
success "Created .keel/keel.config.yml"

# Jira config
cat > "$KEEL_CONFIG_DIR/config/jira.yml" << 'EOF'
# Jira Integration Configuration
jira:
  url: "https://company.atlassian.net"
  email: "user@company.com"
  # API token stored in: ~/.keel/secrets/jira.token

integrations:
  sync_issues: true
  auto_create_pr: true
  update_on_deploy: true

features:
  board_sync: true
  epic_tracking: true
  custom_fields: true

mcp:
  provider: "atlassian"
  endpoint: "https://api.atlassian.com"
EOF
success "Created .keel/config/jira.yml"

# Playwright config
cat > "$KEEL_CONFIG_DIR/config/playwright.yml" << 'EOF'
# Playwright E2E Testing Configuration
playwright:
  headless: true
  timeout: 30000
  retries: 2

browsers:
  chromium: true
  firefox: false
  webkit: false

screenshot_on_failure: true
trace_on_failure: true
video_on_failure: true

devices:
  - desktop
  # - tablet
  # - mobile

mcp:
  provider: "playwright"
  capabilities:
    browser_automation: true
    e2e_testing: true
    screenshot: true
    video_recording: true
EOF
success "Created .keel/config/playwright.yml"

# GitHub config
cat > "$KEEL_CONFIG_DIR/config/github.yml" << 'EOF'
# GitHub Integration Configuration
github:
  repository: "mycompany/my-project"
  # Token stored in: ~/.keel/secrets/github.token

features:
  sync_prs: true
  auto_create_release: true
  update_issues: true
  post_comments: true
  branch_protection: true

workflows:
  auto_approve_dependabot: false
  run_tests_on_pr: true
  deploy_on_release: false

mcp:
  provider: "github"
  api_version: "2022-11-28"
EOF
success "Created .keel/config/github.yml"

# .gitignore
cat > ".gitignore" << 'EOF'
.keel/secrets
node_modules
.env
.env.local
coverage
dist
build
EOF
success "Created .gitignore"

echo ""

# ==============================================================================
# SHOW GENERATED FILES
# ==============================================================================
section_header "Generated Configuration Files"

echo -e "${BLUE}Directory structure:${NC}"
echo ""
tree -L 2 "$KEEL_CONFIG_DIR" 2>/dev/null || find "$KEEL_CONFIG_DIR" -type f | sed 's|^|  |'
echo ""

echo -e "${BLUE}Main config file (.keel/keel.config.yml):${NC}"
echo ""
cat "$KEEL_CONFIG_DIR/keel.config.yml" | head -20
echo "  ..."
echo ""

echo -e "${BLUE}Jira integration (.keel/config/jira.yml):${NC}"
echo ""
cat "$KEEL_CONFIG_DIR/config/jira.yml"
echo ""

echo -e "${BLUE}Playwright integration (.keel/config/playwright.yml):${NC}"
echo ""
cat "$KEEL_CONFIG_DIR/config/playwright.yml"
echo ""

echo -e "${BLUE}GitHub integration (.keel/config/github.yml):${NC}"
echo ""
cat "$KEEL_CONFIG_DIR/config/github.yml"
echo ""

# ==============================================================================
# COMPLETION SUMMARY
# ==============================================================================
section_header "Setup Complete! ✅"

echo -e "${GREEN}Configuration Summary:${NC}"
echo "  Project Name: my-keel-project"
echo "  Tech Stack: cakephp"
echo "  Installation: claude-code-skill"
echo ""

echo -e "${GREEN}Integrations Configured:${NC}"
echo "  ✅ Jira"
echo "  ✅ Playwright"
echo "  ✅ GitHub"
echo "  ⭕ Slack"
echo ""

echo -e "${GREEN}Configuration Files Created:${NC}"
echo "  📁 .keel/keel.config.yml (main config)"
echo "  📁 .keel/config/jira.yml"
echo "  📁 .keel/config/playwright.yml"
echo "  📁 .keel/config/github.yml"
echo "  📁 .gitignore"
echo ""

echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "  1. Restart Claude Code"
echo "  2. Run: /keel init --mode=new --stack=cakephp"
echo "  3. Keel will automatically:"
echo "     • Sync with Jira for issue tracking"
echo "     • Use Playwright for E2E testing"
echo "     • Integrate with GitHub for PR management"
echo ""

echo -e "${GREEN}📊 Configuration Locations:${NC}"
echo "  Main config: $(pwd)/.keel/keel.config.yml"
echo "  Jira config: $(pwd)/.keel/config/jira.yml"
echo "  Playwright config: $(pwd)/.keel/config/playwright.yml"
echo "  GitHub config: $(pwd)/.keel/config/github.yml"
echo "  Secrets storage: ~/.keel/secrets/"
echo ""

echo -e "${GREEN}🎉 Setup wizard completed successfully!${NC}"
echo ""

# ==============================================================================
# SHOW FILE SIZES
# ==============================================================================
echo ""
echo -e "${BLUE}File Summary:${NC}"
echo ""
echo "Configuration files created:"
find "$KEEL_CONFIG_DIR" -type f -exec wc -l {} + | sort -n
echo ""

# ==============================================================================
# SHOW INTEGRATION STATUS
# ==============================================================================
echo -e "${BLUE}Integration Status:${NC}"
echo ""
echo "  Jira:"
echo "    Status: ✅ Configured"
echo "    URL: https://company.atlassian.net"
echo "    MCP: atlassian (requires authentication)"
echo ""
echo "  Playwright:"
echo "    Status: ✅ Configured"
echo "    Browsers: Chromium ✓"
echo "    MCP: playwright (ready to use)"
echo ""
echo "  GitHub:"
echo "    Status: ✅ Configured"
echo "    Repo: mycompany/my-project"
echo "    MCP: github (requires PAT)"
echo ""
echo "  Slack:"
echo "    Status: ⭕ Not configured"
echo "    To enable: Add webhook URL to .keel/config/slack.yml"
echo ""

# ==============================================================================
# TEST COMPLETED
# ==============================================================================
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   TEST COMPLETED ✅                            ║"
echo "║                                                                ║"
echo "║  Configuration files created in: $TEST_DIR                 ║"
echo "║  Ready for production use!                                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📁 Test directory: $TEST_DIR"
echo ""
echo "To use these configurations with real Keel:"
echo "  1. Copy .keel/ directory to your project"
echo "  2. Add API tokens to ~/.keel/secrets/"
echo "  3. Run: /keel init --mode=new --stack=cakephp"
echo ""
